if(NOT DEFINED INPUT OR NOT EXISTS "${INPUT}")
  message(FATAL_ERROR "EmbedSpirv.cmake requires an existing INPUT")
endif()
if(NOT DEFINED OUTPUT)
  message(FATAL_ERROR "EmbedSpirv.cmake requires OUTPUT")
endif()

file(READ "${INPUT}" _hex HEX)
string(LENGTH "${_hex}" _hex_length)
math(EXPR _byte_length "${_hex_length} / 2")
math(EXPR _word_count "${_byte_length} / 4")
math(EXPR _remainder "${_byte_length} % 4")
if(NOT _remainder EQUAL 0)
  message(FATAL_ERROR "SPIR-V byte size must be divisible by four")
endif()

set(_content "#pragma once\n\n#include <cstddef>\n#include <cstdint>\n\nnamespace accloud::render3d::compute::generated {\n\ninline constexpr std::uint32_t kSupportOverlapSpirv[] = {\n")
set(_offset 0)
while(_offset LESS _hex_length)
  string(SUBSTRING "${_hex}" ${_offset} 2 _b0)
  math(EXPR _o1 "${_offset} + 2")
  math(EXPR _o2 "${_offset} + 4")
  math(EXPR _o3 "${_offset} + 6")
  string(SUBSTRING "${_hex}" ${_o1} 2 _b1)
  string(SUBSTRING "${_hex}" ${_o2} 2 _b2)
  string(SUBSTRING "${_hex}" ${_o3} 2 _b3)
  string(APPEND _content "  0x${_b3}${_b2}${_b1}${_b0}u,\n")
  math(EXPR _offset "${_offset} + 8")
endwhile()
string(APPEND _content "};\ninline constexpr std::size_t kSupportOverlapSpirvWordCount = sizeof(kSupportOverlapSpirv) / sizeof(kSupportOverlapSpirv[0]);\n\n} // namespace accloud::render3d::compute::generated\n")

get_filename_component(_output_dir "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_output_dir}")
file(WRITE "${OUTPUT}" "${_content}")
